(defpackage #:aoc-test/day-17
  (:use #:cl #:lisp-unit2 #:aoc/day-17))
(in-package #:aoc-test/day-17)

(define-test test-day-17
    ()
  (let ((registers (make-registers 0 0 9))
        (program (vector 2 6)))
    (aoc/day-17:run-program registers program)
    (assert= 1 (aref registers 1)))
  (let ((registers (make-registers 10 0 0))
        (program (vector 5 0 5 1 5 4)))
    (assert-equal (list 0 1 2)
                  (nreverse (run-program registers program))))
  (let ((registers (make-registers 2024 0 0))
        (program (vector 0 1 5 4 3 0)))
    (assert-equal (list 4 2 5 6 7 7 7 7 3 1 0)
                  (nreverse (run-program registers program)))
    (assert= 0 (aref registers 0)))
  (let ((registers (make-registers 0 29 0))
        (program (vector 1 7)))
    (run-program registers program)
    (assert= 26 (aref registers 1)))
  (let ((registers (make-registers 0 2024 43690))
        (program (vector 4 0)))
    (run-program registers program)
    (assert= 44354 (aref registers 1)))
  (let ((registers (make-registers 729))
        (program (vector 0 1 5 4 3 0)))
    (assert-equal (list 4 6 3 5 6 3 5 2 1 0)
                  (nreverse (run-program registers program)))))
