(defpackage #:aoc-test/day-8
  (:use #:cl #:lisp-unit2)
  (:import-from #:aoc/day-8))
(in-package #:aoc-test/day-8)

(define-test test-day-8
    ()
  (multiple-value-bind (task-1 task-2)
      (aoc:run-day 8 "............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............")
    (assert= 14 task-1)
    (assert= 34 task-2)))
