(defpackage #:aoc-test/day-17
  (:use #:cl #:lisp-unit2 #:aoc/day-17))
(in-package #:aoc-test/day-17)

(defun day-17-tests ()
  (let ((registers (make-registers 0 0 9))
        (program (make-program (vector 2 6))))
    (funcall program registers)
    (assert= 1 (aref registers 1)))
  (let ((registers (make-registers 10 0 0))
        (program (make-program (vector 5 0 5 1 5 4))))
    (assert-equal (list 0 1 2)
                  (nreverse (funcall program registers))))
  (let ((registers (make-registers 2024 0 0))
        (program (make-program (vector 0 1 5 4 3 0))))
    (assert-equal (list 4 2 5 6 7 7 7 7 3 1 0)
                  (nreverse (funcall program registers)))
    (assert= 0 (aref registers 0)))
  (let ((registers (make-registers 0 29 0))
        (program (make-program (vector 1 7))))
    (funcall program registers)
    (assert= 26 (aref registers 1)))
  (let ((registers (make-registers 0 2024 43690))
        (program (make-program (vector 4 0))))
    (funcall program registers)
    (assert= 44354 (aref registers 1)))
  (let ((registers (make-registers 729))
        (program (make-program (vector 0 1 5 4 3 0))))
    (assert-equal (list 4 6 3 5 6 3 5 2 1 0)
                  (nreverse (funcall program registers)))))

(define-test test-day-17
    ()
  (day-17-tests)
  (let ((*use-compiler* t))
    (day-17-tests)))
